# config
logo: /images/svdb.png
keywords: "personal site"
pubkey: 
menu:
  Home: /
  Articles: /articles
  About: /about

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics:
